import type { Metadata } from "next";
import "./globals.css";

/**
 * No next/font/google here, deliberately.
 *
 * The bible makes offline-capable a hard requirement, and every asset in this
 * project is generated by the game's own code. Fetching a webfont at build
 * time contradicts both — and it is a real failure mode: an offline build box
 * simply cannot resolve fonts.googleapis.com and the whole app fails to
 * compile. The storybook type is defined as a CSS stack in globals.css
 * (--font-park), backed by whatever warm rounded face the device already has.
 */
export const metadata: Metadata = {
  title: "ChessPaa's Wonderland",
  description:
    "A warm little theme park at golden-hour dusk, where a grandfather named ChessPaa teaches children to play chess.",
  icons: { icon: "/logo1.png" },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
